# Enter the URI of the manually created ECR repo that hosts the initial ghost image
FROM ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ghost:latest 

# Default port that the ghost app is running
EXPOSE 2368